language: python
python:
  - "2.7"

services:
  - cassandra
  - elasticsearch

os:
  - linux

virtualenv:
  system_site_packages: false

before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/2.1.3/apache-cassandra-2.1.3-bin.tar.gz && tar -xvzf apache-cassandra-2.1.3-bin.tar.gz && mkdir -p apache-cassandra-2.1.3/conf/triggers
  - wget https://github.com/felipead/cassandra-logger/releases/download/v0.2/cassandra-logger-0.2.jar && cp cassandra-logger-0.2.jar apache-cassandra-2.1.3/conf/triggers
  - sudo sh apache-cassandra-2.1.3/bin/cassandra

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

script:
  - py.test
