language: python
python:
  - "2.7"

services:
  - cassandra

os:
  - linux

virtualenv:
  system_site_packages: false

before_install:
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://github.com/felipead/cassandra-logger/releases/download/v0.2/cassandra-logger-0.2.jar && cp cassandra-logger-0.2.jar /var/lib/cassandra/conf/triggers/

install:
  - pip install -r requirements.txt
  - pip install -r requirements.test.txt

script:
  - py.test
